FROM archlinux
RUN pacman -Syuu --noconfirm
RUN pacman -S emacs --noconfirm
RUN pacman -S git ripgrep fd --noconfirm
RUN git clone https://github.com/hlissner/doom-emacs ~/.emacs.d

RUN echo -e "y\ny" | ~/.emacs.d/bin/doom install


CMD ["bin/emacs"]
